[build-system]
requires = [
    "setuptools>=42",
    "charset-normalizer==2.0.9",
    "colorama==0.4.4",
    "polib==1.1.1",
    "requests==2.26.0",
    "progressbar2==3.55.0",
    "wheel"
]
build-backend = "setuptools.build_meta"